In [1]:
import pandas as pd

In [2]:
a=[1,5,7,8]
a1=pd.Series(a,index=["A","B","C","D"])
print(a1)

A    1
B    5
C    7
D    8
dtype: int64


In [3]:
b={
    "studentName":["raj","ravi","sita"],
    "studentCourse":["AI","ML","python"],
    "studentId":[101,102,103]
}
b1=pd.DataFrame(b,index=["X","y","z"])
print(b1.loc["X"])

studentName      raj
studentCourse     AI
studentId        101
Name: X, dtype: object


In [4]:
dataset=pd.read_csv("Data.csv")
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [5]:
x=dataset['Age'].mean()
dataset.fillna({'Age':x},inplace=True)
print(dataset)

   Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
4  Germany  40.000000      NaN       Yes
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes


In [6]:
y=dataset['Salary'].median()
dataset.fillna({'Salary':y},inplace=True)
print(dataset)

   Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
4  Germany  40.000000  61000.0       Yes
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes


In [7]:
dataset.loc[6,'Age']=38
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [8]:
print(dataset.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool


In [9]:
dataset.drop_duplicates(inplace=True)
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [10]:
import numpy as np
print(np.__version__)

2.4.3


In [11]:
import numpy as np

a2 = np.array([[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]],
               [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])

for x in np.nditer(a2):
    print(x)

1
2
3
4
5
10
20
30
40
50
11
12
13
14
15
16
17
18
19
20


In [15]:
import numpy as np

a2 = np.array([[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]],
               [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])

for i, x in np.ndenumerate(a2):
    print(i, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 10
(0, 1, 1) 20
(0, 1, 2) 30
(0, 1, 3) 40
(0, 1, 4) 50
(1, 0, 0) 11
(1, 0, 1) 12
(1, 0, 2) 13
(1, 0, 3) 14
(1, 0, 4) 15
(1, 1, 0) 16
(1, 1, 1) 17
(1, 1, 2) 18
(1, 1, 3) 19
(1, 1, 4) 20


In [16]:
a=np.array([1,2,3,4,5])
print(a[1:5:2])

[2 4]


In [19]:
import numpy as np

a = np.array([
    [1,2,3,4,5,6,7,8,9,10],
    [2,3,5,6,0,0,0,0,0,0],
    [5,6,7,8,9,10,0,0,0,0],
    [1,3,5,7,9,0,0,0,0,0]
])

print(a[0:3, 1:5])

[[2 3 4 5]
 [3 5 6 0]
 [6 7 8 9]]


In [20]:
a = np.array([
    [11,12,13,14,15,16,17,18],
    [2,5,6,9,2,4,3,2],
    [5,1,6,9,2,0,1,2],
    [1,9,6,7,8,2,4,6],
    [6,7,8,9,2,4,6,3]
])

result = a[0:5:2, :4]
print(result)

[[11 12 13 14]
 [ 5  1  6  9]
 [ 6  7  8  9]]


In [21]:
a2 = np.array([
    [[1, 2, 3, 4, 5],
     [10, 20, 30, 40, 50]],
    
    [[11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20]]
])

print(a2.shape)   # to see dimensions

for index, value in np.ndenumerate(a2):
    print(index, value)

(2, 2, 5)
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 10
(0, 1, 1) 20
(0, 1, 2) 30
(0, 1, 3) 40
(0, 1, 4) 50
(1, 0, 0) 11
(1, 0, 1) 12
(1, 0, 2) 13
(1, 0, 3) 14
(1, 0, 4) 15
(1, 1, 0) 16
(1, 1, 1) 17
(1, 1, 2) 18
(1, 1, 3) 19
(1, 1, 4) 20


In [27]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(2,2,3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
